---
- hosts: web
  name: Install the apache web service
  become: yes
  tasks:
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      ansible.posix.selinux:
        policy: targeted
        state: permissive
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present
    - name: Install nginx
      yum:
        name: nginx
        state: present
    - name: Start NGiNX
      service:
        name: nginx
        state: started
    - name: be sure nginx is enabled
      systemd:
        name=nginx
        enabled=yes
    - name: Stop Firewall
      service:
        name: firewalld
        state: stopped
    - name: be sure firewalld is disabled
      systemd:
        name=firewalld
        enabled=no
